name: dddart
description: Some simple DDD dart tools I use.
version: 0.0.2
homepage: https://github.com/seanmccleary/dddart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  uuid: ^4.5.1
  logging: ^1.3.0
  lints: ^5.0.0
dev_dependencies:
  test: ^1.25.8
